enum COMMANDS {
  START_SCREENCAST = 'Page.startScreencast',
  STOP_SCREENCAST = 'Page.stopScreencast',
  SCREENCAST_FRAME_ACK = 'Page.screencastFrameAck',
  INPUT_EMULATE_TOUCH_FROM_MOUSE_EVENT = 'Input.emulateTouchFromMouseEvent',
  INPUT_DISPATCH_KEY_EVENT = 'Input.dispatchKeyEvent',

  SET_VIEWPORT = 'Page.setViewport',
  GO_BACK = 'Page.goBack',
  GO_FORWARD = 'Page.goForward',
  RELOAD = 'Page.reload',

  REGISTER_SCREENCAST = 'Live.registerScreencast',
  RENDER_TABS = 'Live.renderTabs',
  GO_TO_TAB = 'Live.goToTab',
  CLOSE_TAB = 'Live.closeTab',
  KEEP_ALIVE = 'Live.keepAlive',

  FRAME_NAVIGATED = 'Page.frameNavigated',
  SCREENCAST_FRAME = 'Page.screencastFrame',

  SCREENCAST_REGISTERED = 'Live.screencastRegistered',
  TARGET_CREATED = 'Target.created',
  TARGET_DESTROYED = 'Target.destroyed',
  TARGET_BRING_TO_FRONT = 'Target.bringToFront',
}

export const LIVE_CLIENT = {
  COMMANDS: {
    // session
    REGISTER_SCREENCAST: COMMANDS.REGISTER_SCREENCAST,
    KEEP_ALIVE: COMMANDS.KEEP_ALIVE,
    // tabs
    GO_TO_TAB: COMMANDS.GO_TO_TAB,
    CLOSE_TAB: COMMANDS.CLOSE_TAB,
    // navigation
    GO_BACK: COMMANDS.GO_BACK,
    GO_FORWARD: COMMANDS.GO_FORWARD,
    RELOAD: COMMANDS.RELOAD,
    // screencast
    SCREENCAST_FRAME_ACK: COMMANDS.SCREENCAST_FRAME_ACK,
    // page control
    INPUT_EMULATE_TOUCH_FROM_MOUSE_EVENT: COMMANDS.INPUT_EMULATE_TOUCH_FROM_MOUSE_EVENT,
    INPUT_DISPATCH_KEY_EVENT: COMMANDS.INPUT_DISPATCH_KEY_EVENT,
    SET_VIEWPORT: COMMANDS.SET_VIEWPORT,
  },
  EVENTS: {
    SCREENCAST_REGISTERED: COMMANDS.SCREENCAST_REGISTERED,
    SCREENCAST_FRAME: COMMANDS.SCREENCAST_FRAME,
    TARGET_CREATED: COMMANDS.TARGET_CREATED,
    TARGET_DESTROYED: COMMANDS.TARGET_DESTROYED,
    TARGET_BRING_TO_FRONT: COMMANDS.TARGET_BRING_TO_FRONT,
    FRAME_NAVIGATED: COMMANDS.FRAME_NAVIGATED,
  },
} as const;

export const LIVE_SERVER = {
  COMMANDS: {
    SCREENCAST_REGISTERED: COMMANDS.SCREENCAST_REGISTERED,
    TARGET_CREATED: COMMANDS.TARGET_CREATED,
    TARGET_DESTROYED: COMMANDS.TARGET_DESTROYED,
    TARGET_BRING_TO_FRONT: COMMANDS.TARGET_BRING_TO_FRONT,
    FRAME_NAVIGATED: COMMANDS.FRAME_NAVIGATED,
    SCREENCAST_FRAME: COMMANDS.SCREENCAST_FRAME,
  },
  EVENTS: {
    REGISTER_SCREENCAST: COMMANDS.REGISTER_SCREENCAST,
    GO_TO_TAB: COMMANDS.GO_TO_TAB,
    CLOSE_TAB: COMMANDS.CLOSE_TAB,
    KEEP_ALIVE: COMMANDS.KEEP_ALIVE,
    SET_VIEWPORT: COMMANDS.SET_VIEWPORT,
    GO_BACK: COMMANDS.GO_BACK,
    GO_FORWARD: COMMANDS.GO_FORWARD,
    RELOAD: COMMANDS.RELOAD,
    SCREENCAST_FRAME_ACK: COMMANDS.SCREENCAST_FRAME_ACK,
    INPUT_EMULATE_TOUCH_FROM_MOUSE_EVENT: COMMANDS.INPUT_EMULATE_TOUCH_FROM_MOUSE_EVENT,
    INPUT_DISPATCH_KEY_EVENT: COMMANDS.INPUT_DISPATCH_KEY_EVENT,
  },
  CDP_COMMANDS: {
    START_SCREENCAST: COMMANDS.START_SCREENCAST,
    STOP_SCREENCAST: COMMANDS.STOP_SCREENCAST,
  },
  CDP_EVENTS: {
    SCREENCAST_FRAME: COMMANDS.SCREENCAST_FRAME,
  },
} as const;

export const DEFAULT_KEEP_ALIVE_TIMEOUT = 1000 * 60 * 5; // 5 minutes
