export const DEFAULT_PAGE_TIMEOUT = 30000;

export const HEADLESS_PAGE_IDENTIFIER = 'HEADLESS';

export const DEFAULT_LAUNCH_ARGS = [
  '--disable-setuid-sandbox',
  '--disable-dev-shm-usage',
  '--disable-features=site-per-process,AudioServiceOutOfProcess,Translate,OptimizationHints,MediaRouter,DialMediaRouteProvider,CalculateNativeWinOcclusion,InterestFeedContentSuggestions,CertificateTransparencyComponentUpdater,AutofillServerCommunication,PrivacySandboxSettings4,RenderDocument',
  '--disable-component-extensions-with-background-pages',
  '--disable-backgrounding-occluded-windows',
  '--disable-ipc-flooding-protection',
  '--disable-hang-monitor',
  /* Disable animations to reduce time waiting for animations to complete */
  '--disable-modal-animations',
  '--disable-popup-blocking',
  '--disable-speech-api',
  '--disable-breakpad',
  '--disable-component-update',
  '--disable-default-apps',
  '--disable-domain-reliability',
  '--disable-notifications',
  '--disable-offer-store-unmasked-wallet-cards',
  '--disable-client-side-phishing-detection',
  '--disable-print-preview',
  '--disable-prompt-on-repost',
  '--disable-background-timer-throttling',
  '--disable-renderer-backgrounding',
  '--disable-sync',
  '--disable-software-rasterizer',
  '--no-first-run',
  '--no-startup-window',
  '--no-sandbox',
  '--no-zygote',
  '--no-default-browser-check',
  '--no-pings',
  '--mute-audio',
  '--wm-window-animations-disabled',
  '--use-gl=swiftshader',
  '--password-store=basic',
  '--use-mock-keychain',
  '--force-fieldtrials=*BackgroundTracing/default/',
];
