export const ACTIONS = {
  START_RECORDING: 'START_RECORDING',
  STOP_RECORDING: 'STOP_RECORDING',
  BEGIN_DOWNLOAD: 'BEGIN_DOWNLOAD',
  COMPLETE_DOWNLOAD: 'COMPLETE_DOWNLOAD',
} as const;

export const DEFAULT_SAMPLE_RATE = 44100;
